name: Cloudstream Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          path: 'src'

      - name: Checkout Builds Branch
        uses: actions/checkout@v3
        with:
          ref: 'builds'
          path: 'builds'
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Plugins
        working-directory: 'src'
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson

      - name: Push to Builds Branch
        run: |
          mkdir -p builds
          cp src/build/*.cs3 builds/
          cp src/build/plugins.json builds/
          cd builds
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git init
          git checkout -b builds || git checkout builds
          git add .
          git commit -m "Update builds: ${GITHUB_SHA::8}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} builds --force
